services:
  mongodb:
    image: mongo:5.0
    container_name: ce_mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/data:/data/db
    env_file:
      - ./docker/mongodb/.env-mongodb
  mongo_express:
    image: mongo-express:0.54
    container_name: ce_mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    env_file:
      - ./docker/mongodb/.env-mongo-express
  api:
    image: node:16-alpine
    container_name: ce_api
    depends_on:
      - mongo_express
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "yarn && yarn nodemon"
  mobile:
    build: ./mobile
    container_name: ce_mobile
    depends_on:
      - api
    ports:
      - 19000:19000
    volumes:
      - ./mobile:/app
    working_dir: /app
    command: sh -c "yarn && yarn start"
